import type {
  CategoryReviewStatus,
  CompanyDataModel,
  DashboardCompanyRow,
  HistoricalPeriod,
  ReviewSeverity,
} from "@/lib/types";

const standardHistoricalPeriods: HistoricalPeriod[] = [
  "YEAR_MINUS_4",
  "YEAR_MINUS_3",
  "YEAR_MINUS_2",
  "LATEST_FY",
  "LTM",
];

function buildCategoryStatuses(defaultSeverity: ReviewSeverity): CategoryReviewStatus {
  return {
    "Forecast Quality": defaultSeverity,
    "Fade Quality": defaultSeverity,
    "Terminal Readiness": defaultSeverity,
    "Financial Health": defaultSeverity,
    "Business Quality": defaultSeverity,
    "Share Count Review": defaultSeverity,
    "SBC Dilution Review": defaultSeverity,
    "Currency Review": defaultSeverity,
    "Data Completeness": defaultSeverity,
    Governance: defaultSeverity,
  };
}

export const mockCompanies: CompanyDataModel[] = [
  {
    identity: {
      companyName: "Microsoft",
      fullTicker: "MSFT:NASDAQ",
      cleanTicker: "MSFT",
      exchange: "NASDAQ",
      websiteDomain: "microsoft.com",
      websiteUrl: "https://www.microsoft.com",
      logoUrl: "https://logo.clearbit.com/microsoft.com",
      ismSector: "Information Technology",
      damodaranIndustrialBenchmark: "Software (System & Application)",
      countryOfRisk: "United States",
    },
    currencies: {
      valuationCurrency: "USD",
      reportingCurrency: "USD",
      tradingCurrency: "USD",
      fxPairToValuation: "USDUSD",
      reviewStatus: "Aligned",
      note: "No FX conversion needed for base case.",
    },
    companySetupInputs: {
      companyName: "Microsoft",
      fullTicker: "MSFT:NASDAQ",
      cleanTicker: "MSFT",
      exchange: "NASDAQ",
      valuationDate: "2026-05-24",
      valuationCurrency: "USD",
      reportingCurrency: "USD",
      tradingCurrency: "USD",
    },
    marketInputs: {
      currentPrice: 432.18,
      marketCap: 3210000000000,
      manualShareCountOverride: undefined,
      historicalWeightedAverageDilutedShares: {
        YEAR_MINUS_4: 7600,
        YEAR_MINUS_3: 7545,
        YEAR_MINUS_2: 7486,
        LATEST_FY: 7442,
        LTM: 7427,
      },
      beta: 1.06,
    },
    historicalData: {
      incomeStatement: {
        revenue: {
          YEAR_MINUS_4: 168088,
          YEAR_MINUS_3: 198270,
          YEAR_MINUS_2: 211915,
          LATEST_FY: 236584,
          LTM: 244131,
        },
        grossProfit: {
          YEAR_MINUS_4: 115856,
          YEAR_MINUS_3: 135620,
          YEAR_MINUS_2: 146052,
          LATEST_FY: 163116,
          LTM: 168002,
        },
        ebitda: {
          YEAR_MINUS_4: 95750,
          YEAR_MINUS_3: 109340,
          YEAR_MINUS_2: 115215,
          LATEST_FY: 126990,
          LTM: 131200,
        },
        ebit: {
          YEAR_MINUS_4: 83200,
          YEAR_MINUS_3: 94810,
          YEAR_MINUS_2: 100420,
          LATEST_FY: 110330,
          LTM: 113850,
        },
        netIncome: {
          YEAR_MINUS_4: 61270,
          YEAR_MINUS_3: 72740,
          YEAR_MINUS_2: 75460,
          LATEST_FY: 87890,
          LTM: 90240,
        },
        eps: {
          YEAR_MINUS_4: 8.05,
          YEAR_MINUS_3: 9.65,
          YEAR_MINUS_2: 10.08,
          LATEST_FY: 11.72,
          LTM: 12.15,
        },
        effectiveTaxRate: {
          YEAR_MINUS_4: 0.14,
          YEAR_MINUS_3: 0.15,
          YEAR_MINUS_2: 0.16,
          LATEST_FY: 0.16,
          LTM: 0.16,
        },
        interestExpense: {
          YEAR_MINUS_4: 2340,
          YEAR_MINUS_3: 2460,
          YEAR_MINUS_2: 2510,
          LATEST_FY: 2650,
          LTM: 2690,
        },
        sbc: {
          YEAR_MINUS_4: 7800,
          YEAR_MINUS_3: 8450,
          YEAR_MINUS_2: 9020,
          LATEST_FY: 9640,
          LTM: 9880,
        },
        dividendsPerShare: {
          YEAR_MINUS_4: 2.3,
          YEAR_MINUS_3: 2.48,
          YEAR_MINUS_2: 2.72,
          LATEST_FY: 3,
          LTM: 3.08,
        },
      },
      cashFlow: {
        operatingCashFlow: {
          YEAR_MINUS_4: 76500,
          YEAR_MINUS_3: 89040,
          YEAR_MINUS_2: 94420,
          LATEST_FY: 107000,
          LTM: 109540,
        },
        freeCashFlow: {
          YEAR_MINUS_4: 56120,
          YEAR_MINUS_3: 65310,
          YEAR_MINUS_2: 67900,
          LATEST_FY: 74250,
          LTM: 76020,
        },
        depreciationAndAmortization: {
          YEAR_MINUS_4: 12550,
          YEAR_MINUS_3: 14530,
          YEAR_MINUS_2: 14795,
          LATEST_FY: 16660,
          LTM: 17350,
        },
        capex: {
          YEAR_MINUS_4: 20380,
          YEAR_MINUS_3: 23730,
          YEAR_MINUS_2: 26520,
          LATEST_FY: 32750,
          LTM: 33520,
        },
      },
      workingCapital: {
        receivables: {
          YEAR_MINUS_4: 38000,
          YEAR_MINUS_3: 42500,
          YEAR_MINUS_2: 44900,
          LATEST_FY: 47100,
          LTM: 48220,
        },
        inventory: {
          YEAR_MINUS_4: 2600,
          YEAR_MINUS_3: 2900,
          YEAR_MINUS_2: 3100,
          LATEST_FY: 3500,
          LTM: 3600,
        },
        accountsPayable: {
          YEAR_MINUS_4: 16700,
          YEAR_MINUS_3: 18150,
          YEAR_MINUS_2: 19420,
          LATEST_FY: 20980,
          LTM: 21410,
        },
        deferredRevenue: {
          YEAR_MINUS_4: 39400,
          YEAR_MINUS_3: 42100,
          YEAR_MINUS_2: 43800,
          LATEST_FY: 46950,
          LTM: 48040,
        },
      },
    },
    balanceSheetBridgeInputs: {
      cashAndCashEquivalents: 81500,
      marketableSecurities: 104200,
      grossDebt: 73800,
      leaseLiabilities: 15600,
      minorityInterest: 0,
      preferredEquity: 0,
      pensionDeficit: 0,
      otherClaims: 6200,
    },
    debtDetailInputs: {
      averageDebtMaturityYears: 8.2,
      averageDebtCost: 0.035,
      fixedVsFloatingMixPercent: 82,
      debtCurrencyMix: { USD: 92, EUR: 8 },
    },
    leaseInputs: {
      annualLeaseExpense: 6200,
      leaseDurationYears: 7,
      impliedLeaseDiscountRate: 0.043,
    },
    forecastInputs: {
      revenueGrowthAssumption: 0.1,
      targetOperatingMargin: 0.45,
      targetTaxRate: 0.17,
      targetReinvestmentRate: 0.27,
      targetRoeOrRoic: 0.29,
    },
    riskWaccInputs: {
      riskfreeRate: 0.0415,
      equityRiskPremium: 0.047,
      countryRiskPremium: 0,
      beta: 1.06,
      preTaxCostOfDebt: 0.038,
      targetDebtToCapital: 0.18,
      marginalTaxRate: 0.17,
    },
    betaPolicyInputs: {
      marketDebtToEquity: 0.22,
      selectedTaxRate: 0.17,
    },
    waccFoundationInputs: {
      preTaxCostOfDebt: 0.038,
      costOfDebtSource: "Mock / Foundation scaffold",
      notes: "Scaffold pre-tax cost of debt for WACC foundation QA — not live company data.",
    },
    intrinsicValueFoundationInputs: {
      selectedDilutedShares: 7427,
      shareUnit: "millions",
      selectedSharesSource: "LTM historical weighted average diluted shares (millions)",
      currentSharePrice: 432.18,
      priceCurrency: "USD",
      fxRateToValuationCurrency: 1,
      notes: "Mock / foundation scaffold share count — not live company data.",
    },
    terminalValueInputs: {
      terminalGrowthRate: 0.024,
      terminalRoiOrRoic: 0.18,
      terminalMargin: 0.4,
      terminalMethod: "Hybrid",
    },
    decisionLayerInputs: {
      minimumMOSForApprove: 0.08,
      watchlistMOSFloor: 0.03,
      hardExclusionTags: [],
      analystOverrideNote: "No override currently applied.",
    },
    scenarioSensitivityInputs: {
      baseCaseWeight: 0.6,
      bullCaseWeight: 0.25,
      bearCaseWeight: 0.15,
      discountRateShockBps: 50,
      terminalGrowthShockBps: 30,
    },
    accountingAdjustmentInputs: {
      normalizeOneOffItems: true,
      capitalizeRAndD: false,
      sbcTreatment: "Add Back With Dilution",
      leaseTreatment: "Debt-like",
    },
    forecastData: {
      baseCaseRevenueGrowthByPeriod: {
        YEAR_PLUS_1: 0.11,
        YEAR_PLUS_2: 0.1,
        YEAR_PLUS_3: 0.09,
        YEAR_PLUS_4: 0.08,
        YEAR_PLUS_5: 0.07,
      },
      baseCaseOperatingMarginByPeriod: {
        YEAR_PLUS_1: 0.44,
        YEAR_PLUS_2: 0.445,
        YEAR_PLUS_3: 0.448,
        YEAR_PLUS_4: 0.45,
      },
      capexAsPercentRevenueByPeriod: {
        YEAR_PLUS_1: 0.14,
        YEAR_PLUS_2: 0.135,
        YEAR_PLUS_3: 0.13,
      },
      narrative: "Cloud and productivity remain core growth vectors.",
    },
    valuationResult: {
      forecastFadeResult: {
        revenueGrowthPath: {
          YEAR_PLUS_1: 0.11,
          YEAR_PLUS_2: 0.1,
          YEAR_PLUS_3: 0.09,
          YEAR_PLUS_6: 0.06,
          YEAR_PLUS_10: 0.04,
        },
        operatingMarginPath: {
          YEAR_PLUS_1: 0.44,
          YEAR_PLUS_2: 0.445,
          YEAR_PLUS_3: 0.448,
          YEAR_PLUS_10: 0.41,
        },
        fadeNarrative: "Margin fade to mature software benchmark.",
      },
      reinvestmentFcffResult: {
        reinvestmentRatePath: {
          YEAR_PLUS_1: 0.29,
          YEAR_PLUS_2: 0.28,
          YEAR_PLUS_3: 0.27,
        },
        fcffPath: {
          YEAR_PLUS_1: 80500,
          YEAR_PLUS_2: 86800,
          YEAR_PLUS_3: 93400,
        },
        notes: "Placeholder FCFF path for type readiness only.",
      },
      riskWaccResult: {
        costOfEquity: 0.091,
        costOfDebtAfterTax: 0.031,
        wacc: 0.079,
        beta: 1.06,
        erp: 0.047,
      },
      terminalValueResult: {
        terminalMethod: "Hybrid",
        terminalValue: 2510000,
        terminalGrowthRate: 0.024,
        terminalYear: "YEAR_PLUS_10",
      },
      firmToEquityBridgeResult: {
        enterpriseValue: 3330000,
        cashAndInvestments: 185700,
        totalDebtAndDebtLikeClaims: 95600,
        minorityInterest: 0,
        preferredEquity: 0,
        pensionAndOtherClaims: 6200,
        equityValue: 3413900,
      },
      shareCountResult: {
        historicalWeightedAverageDilutedShares: 7427,
        finalShareCountUsed: 7427,
        sbcDilutionAssumption: 0.01,
      },
      perShareValuationResult: {
        intrinsicValuePerShare: 478.4,
        entryPrice: 389.6,
        exitPrice12m: 452.3,
        return12mFromEntry: 0.161,
        exitPrice3y: 561.9,
        return3yFromEntry: 0.442,
        finalMOS: 0.0966,
      },
      decisionResult: {
        decisionStatus: "Approve",
        statusNote: "Stable growth and high quality cash conversion.",
        blockingFlags: [],
        reviewFlag: {
          category: "Forecast Quality",
          severity: "Info",
          note: "Forecast assumptions are consistent with historical trend.",
        },
      },
      modelVersion: "phase2-placeholder-v1",
      calculatedAt: "2026-05-24",
    },
    reviewSummary: {
      worstSeverity: "Watch",
      contributingCategories: ["SBC Dilution Review"],
      categoryStatuses: {
        ...buildCategoryStatuses("Info"),
        "SBC Dilution Review": "Watch",
      },
      note: "Monitor dilution trend while maintaining positive base-case quality.",
    },
    dashboardRow: {
      companyLogoUrl: "https://logo.clearbit.com/microsoft.com",
      companyName: "Microsoft",
      ticker: "MSFT",
      exchange: "NASDAQ",
      ismSector: "Information Technology",
      damodaranIndustrialBenchmark: "Software (System & Application)",
      currentPrice: 432.18,
      marketCap: 3210000000000,
      valuationCurrency: "USD",
      intrinsicValuePerShare: 478.4,
      finalMOS: 0.0966,
      entryPrice: 389.6,
      exitPrice12m: 452.3,
      return12mFromEntry: 0.161,
      exitPrice3y: 561.9,
      return3yFromEntry: 0.442,
      decisionStatus: "Approve",
      reviewFlag: "Watch",
      statusNote: "Stable growth and high quality cash conversion.",
      beta: 1.06,
      erp: 0.047,
      wacc: 0.079,
      forecastQuality: "Info",
      fadeQuality: "Info",
      terminalReadiness: "Info",
      financialHealth: "Info",
      businessQuality: "Info",
      shareCountReview: "Info",
      sbcDilutionReview: "Watch",
      currencyReview: "Info",
      lastUpdated: "2026-05-24",
      websiteUrl: "https://www.microsoft.com",
      openCompanyUrl: "/companies/MSFT",
    },
    lastUpdated: "2026-05-24",
    availableHistoricalPeriods: standardHistoricalPeriods,
  },
  {
    identity: {
      companyName: "Disney",
      fullTicker: "DIS:NYSE",
      cleanTicker: "DIS",
      exchange: "NYSE",
      websiteDomain: "disney.com",
      websiteUrl: "https://thewaltdisneycompany.com",
      logoUrl: "https://logo.clearbit.com/disney.com",
      ismSector: "Communication Services",
      damodaranIndustrialBenchmark: "Entertainment",
      countryOfRisk: "United States",
    },
    currencies: {
      valuationCurrency: "USD",
      reportingCurrency: "USD",
      tradingCurrency: "USD",
      fxPairToValuation: "USDUSD",
      reviewStatus: "Aligned",
      note: "Global exposure remains but base reporting is USD.",
    },
    companySetupInputs: {
      companyName: "Disney",
      fullTicker: "DIS:NYSE",
      cleanTicker: "DIS",
      exchange: "NYSE",
      valuationDate: "2026-05-24",
      valuationCurrency: "USD",
      reportingCurrency: "USD",
      tradingCurrency: "USD",
    },
    marketInputs: {
      currentPrice: 112.74,
      marketCap: 207000000000,
      historicalWeightedAverageDilutedShares: {
        YEAR_MINUS_4: 1832,
        YEAR_MINUS_3: 1820,
        YEAR_MINUS_2: 1809,
        LATEST_FY: 1800,
        LTM: 1796,
      },
      beta: 1.13,
    },
    historicalData: {
      incomeStatement: {
        revenue: {
          YEAR_MINUS_4: 67418,
          YEAR_MINUS_3: 82722,
          YEAR_MINUS_2: 88600,
          LATEST_FY: 91410,
          LTM: 92850,
        },
        grossProfit: {
          YEAR_MINUS_4: 21400,
          YEAR_MINUS_3: 27820,
          YEAR_MINUS_2: 29850,
          LATEST_FY: 30920,
          LTM: 31480,
        },
        ebitda: {
          YEAR_MINUS_4: 10300,
          YEAR_MINUS_3: 13840,
          YEAR_MINUS_2: 15120,
          LATEST_FY: 16610,
          LTM: 16920,
        },
        ebit: {
          YEAR_MINUS_4: 7040,
          YEAR_MINUS_3: 9600,
          YEAR_MINUS_2: 10840,
          LATEST_FY: 11920,
          LTM: 12130,
        },
        netIncome: {
          YEAR_MINUS_4: 3190,
          YEAR_MINUS_3: 5400,
          YEAR_MINUS_2: 6080,
          LATEST_FY: 6920,
          LTM: 7150,
        },
        eps: {
          YEAR_MINUS_4: 1.74,
          YEAR_MINUS_3: 2.97,
          YEAR_MINUS_2: 3.37,
          LATEST_FY: 3.85,
          LTM: 3.99,
        },
        effectiveTaxRate: {
          YEAR_MINUS_4: 0.22,
          YEAR_MINUS_3: 0.21,
          YEAR_MINUS_2: 0.2,
          LATEST_FY: 0.2,
          LTM: 0.2,
        },
        interestExpense: {
          YEAR_MINUS_4: 1850,
          YEAR_MINUS_3: 1760,
          YEAR_MINUS_2: 1680,
          LATEST_FY: 1610,
          LTM: 1580,
        },
        sbc: {
          YEAR_MINUS_4: 940,
          YEAR_MINUS_3: 980,
          YEAR_MINUS_2: 1020,
          LATEST_FY: 1060,
          LTM: 1090,
        },
        dividendsPerShare: {
          YEAR_MINUS_4: 0,
          YEAR_MINUS_3: 0.3,
          YEAR_MINUS_2: 0.45,
          LATEST_FY: 0.6,
          LTM: 0.7,
        },
      },
      cashFlow: {
        operatingCashFlow: {
          YEAR_MINUS_4: 7310,
          YEAR_MINUS_3: 9640,
          YEAR_MINUS_2: 10220,
          LATEST_FY: 11590,
          LTM: 11940,
        },
        freeCashFlow: {
          YEAR_MINUS_4: 1540,
          YEAR_MINUS_3: 3260,
          YEAR_MINUS_2: 4120,
          LATEST_FY: 5630,
          LTM: 5840,
        },
        depreciationAndAmortization: {
          YEAR_MINUS_4: 3260,
          YEAR_MINUS_3: 4240,
          YEAR_MINUS_2: 4280,
          LATEST_FY: 4690,
          LTM: 4790,
        },
        capex: {
          YEAR_MINUS_4: 5770,
          YEAR_MINUS_3: 6380,
          YEAR_MINUS_2: 6100,
          LATEST_FY: 5960,
          LTM: 6100,
        },
      },
      workingCapital: {
        receivables: {
          YEAR_MINUS_4: 11100,
          YEAR_MINUS_3: 11800,
          YEAR_MINUS_2: 12250,
          LATEST_FY: 12780,
          LTM: 13010,
        },
        inventory: {
          YEAR_MINUS_4: 1700,
          YEAR_MINUS_3: 1760,
          YEAR_MINUS_2: 1800,
          LATEST_FY: 1880,
          LTM: 1910,
        },
        accountsPayable: {
          YEAR_MINUS_4: 8140,
          YEAR_MINUS_3: 8520,
          YEAR_MINUS_2: 8760,
          LATEST_FY: 9010,
          LTM: 9190,
        },
        deferredRevenue: {
          YEAR_MINUS_4: 5320,
          YEAR_MINUS_3: 5660,
          YEAR_MINUS_2: 5980,
          LATEST_FY: 6210,
          LTM: 6400,
        },
      },
    },
    balanceSheetBridgeInputs: {
      cashAndCashEquivalents: 10920,
      marketableSecurities: 4180,
      grossDebt: 47200,
      leaseLiabilities: 9600,
      minorityInterest: 1400,
      preferredEquity: 0,
      pensionDeficit: 2800,
      otherClaims: 1900,
    },
    debtDetailInputs: {
      averageDebtMaturityYears: 10.4,
      averageDebtCost: 0.041,
      fixedVsFloatingMixPercent: 76,
      debtCurrencyMix: { USD: 89, EUR: 7, GBP: 4 },
    },
    leaseInputs: {
      annualLeaseExpense: 2450,
      leaseDurationYears: 8,
      impliedLeaseDiscountRate: 0.048,
    },
    forecastInputs: {
      revenueGrowthAssumption: 0.065,
      targetOperatingMargin: 0.17,
      targetTaxRate: 0.21,
      targetReinvestmentRate: 0.34,
      targetRoeOrRoic: 0.12,
    },
    riskWaccInputs: {
      riskfreeRate: 0.0415,
      equityRiskPremium: 0.047,
      countryRiskPremium: 0,
      beta: 1.13,
      preTaxCostOfDebt: 0.047,
      targetDebtToCapital: 0.34,
      marginalTaxRate: 0.21,
    },
    betaPolicyInputs: {
      selectedTaxRate: 0.21,
    },
    waccFoundationInputs: {
      notes:
        "Intentionally no pre-tax cost of debt scaffold — tests WACC Review/Missing without synthetic rating.",
    },
    intrinsicValueFoundationInputs: {
      selectedDilutedShares: 1796,
      shareUnit: "millions",
      selectedSharesSource: "LTM historical weighted average diluted shares (millions)",
      currentSharePrice: 118.4,
      priceCurrency: "USD",
      fxRateToValuationCurrency: 1,
      notes: "Mock / foundation scaffold share count — not live company data.",
    },
    terminalValueInputs: {
      terminalGrowthRate: 0.022,
      terminalRoiOrRoic: 0.1,
      terminalMargin: 0.15,
      terminalMethod: "Gordon Growth",
    },
    decisionLayerInputs: {
      minimumMOSForApprove: 0.1,
      watchlistMOSFloor: 0.04,
      hardExclusionTags: [],
    },
    scenarioSensitivityInputs: {
      baseCaseWeight: 0.55,
      bullCaseWeight: 0.25,
      bearCaseWeight: 0.2,
      discountRateShockBps: 75,
      terminalGrowthShockBps: 40,
    },
    accountingAdjustmentInputs: {
      normalizeOneOffItems: true,
      capitalizeRAndD: false,
      sbcTreatment: "As Expense",
      leaseTreatment: "Debt-like",
    },
    forecastData: {
      baseCaseRevenueGrowthByPeriod: {
        YEAR_PLUS_1: 0.07,
        YEAR_PLUS_2: 0.068,
        YEAR_PLUS_3: 0.062,
        YEAR_PLUS_4: 0.055,
      },
      baseCaseOperatingMarginByPeriod: {
        YEAR_PLUS_1: 0.145,
        YEAR_PLUS_2: 0.153,
        YEAR_PLUS_3: 0.16,
      },
      capexAsPercentRevenueByPeriod: {
        YEAR_PLUS_1: 0.066,
        YEAR_PLUS_2: 0.064,
        YEAR_PLUS_3: 0.062,
      },
      narrative: "Streaming breakeven and parks resilience drive outlook.",
    },
    valuationResult: {
      forecastFadeResult: {
        revenueGrowthPath: {
          YEAR_PLUS_1: 0.07,
          YEAR_PLUS_2: 0.068,
          YEAR_PLUS_3: 0.062,
          YEAR_PLUS_7: 0.04,
          YEAR_PLUS_10: 0.03,
        },
        operatingMarginPath: {
          YEAR_PLUS_1: 0.145,
          YEAR_PLUS_2: 0.153,
          YEAR_PLUS_3: 0.16,
          YEAR_PLUS_10: 0.145,
        },
        fadeNarrative: "Converges toward entertainment benchmark margins.",
      },
      reinvestmentFcffResult: {
        reinvestmentRatePath: {
          YEAR_PLUS_1: 0.36,
          YEAR_PLUS_2: 0.35,
          YEAR_PLUS_3: 0.34,
        },
        fcffPath: {
          YEAR_PLUS_1: 6200,
          YEAR_PLUS_2: 7010,
          YEAR_PLUS_3: 7680,
        },
        notes: "Placeholder FCFF path only.",
      },
      riskWaccResult: {
        costOfEquity: 0.095,
        costOfDebtAfterTax: 0.037,
        wacc: 0.082,
        beta: 1.13,
        erp: 0.047,
      },
      terminalValueResult: {
        terminalMethod: "Gordon Growth",
        terminalValue: 168000,
        terminalGrowthRate: 0.022,
        terminalYear: "YEAR_PLUS_10",
      },
      firmToEquityBridgeResult: {
        enterpriseValue: 221500,
        cashAndInvestments: 15100,
        totalDebtAndDebtLikeClaims: 56800,
        minorityInterest: 1400,
        preferredEquity: 0,
        pensionAndOtherClaims: 4700,
        equityValue: 173700,
      },
      shareCountResult: {
        historicalWeightedAverageDilutedShares: 1796,
        finalShareCountUsed: 1796,
        sbcDilutionAssumption: 0.008,
      },
      perShareValuationResult: {
        intrinsicValuePerShare: 124.1,
        entryPrice: 95.2,
        exitPrice12m: 118.6,
        return12mFromEntry: 0.246,
        exitPrice3y: 143.4,
        return3yFromEntry: 0.506,
        finalMOS: 0.0915,
      },
      decisionResult: {
        decisionStatus: "Watchlist",
        statusNote: "Parks strength offsets streaming margin uncertainty.",
        blockingFlags: ["Monitor debt reduction pace."],
        reviewFlag: {
          category: "Forecast Quality",
          severity: "Watch",
          note: "Forecast confidence improving but still transition-heavy.",
        },
      },
      modelVersion: "phase2-placeholder-v1",
      calculatedAt: "2026-05-24",
    },
    reviewSummary: {
      worstSeverity: "Review Required",
      contributingCategories: ["Terminal Readiness", "Financial Health"],
      categoryStatuses: {
        ...buildCategoryStatuses("Watch"),
        "Terminal Readiness": "Review Required",
        "Financial Health": "Review Required",
        Governance: "Info",
      },
      note: "Leverage and terminal assumptions need deeper calibration later.",
    },
    dashboardRow: {
      companyLogoUrl: "https://logo.clearbit.com/disney.com",
      companyName: "Disney",
      ticker: "DIS",
      exchange: "NYSE",
      ismSector: "Communication Services",
      damodaranIndustrialBenchmark: "Entertainment",
      currentPrice: 112.74,
      marketCap: 207000000000,
      valuationCurrency: "USD",
      intrinsicValuePerShare: 124.1,
      finalMOS: 0.0915,
      entryPrice: 95.2,
      exitPrice12m: 118.6,
      return12mFromEntry: 0.246,
      exitPrice3y: 143.4,
      return3yFromEntry: 0.506,
      decisionStatus: "Watchlist",
      reviewFlag: "Review Required",
      statusNote: "Parks strength offsets streaming margin uncertainty.",
      beta: 1.13,
      erp: 0.047,
      wacc: 0.082,
      forecastQuality: "Watch",
      fadeQuality: "Watch",
      terminalReadiness: "Review Required",
      financialHealth: "Review Required",
      businessQuality: "Info",
      shareCountReview: "Info",
      sbcDilutionReview: "Watch",
      currencyReview: "Info",
      lastUpdated: "2026-05-24",
      websiteUrl: "https://thewaltdisneycompany.com",
      openCompanyUrl: "/companies/DIS",
    },
    lastUpdated: "2026-05-24",
    availableHistoricalPeriods: standardHistoricalPeriods,
  },
  {
    identity: {
      companyName: "Volvo",
      fullTicker: "VOLV-B:STO",
      cleanTicker: "VOLV-B",
      exchange: "STO",
      websiteDomain: "volvogroup.com",
      websiteUrl: "https://www.volvogroup.com",
      logoUrl: "https://logo.clearbit.com/volvogroup.com",
      ismSector: "Industrials",
      damodaranIndustrialBenchmark: "Auto & Truck",
      countryOfRisk: "Sweden",
    },
    currencies: {
      valuationCurrency: "SEK",
      reportingCurrency: "SEK",
      tradingCurrency: "SEK",
      fxPairToValuation: "SEKSEK",
      reviewStatus: "Aligned",
      note: "SEK base, but multi-currency end market exposure remains.",
    },
    companySetupInputs: {
      companyName: "Volvo",
      fullTicker: "VOLV-B:STO",
      cleanTicker: "VOLV-B",
      exchange: "STO",
      valuationDate: "2026-05-24",
      valuationCurrency: "SEK",
      reportingCurrency: "SEK",
      tradingCurrency: "SEK",
    },
    marketInputs: {
      currentPrice: 304.5,
      marketCap: 620000000000,
      historicalWeightedAverageDilutedShares: {
        YEAR_MINUS_4: 2040,
        YEAR_MINUS_3: 2030,
        YEAR_MINUS_2: 2022,
        LATEST_FY: 2014,
        LTM: 2010,
      },
      beta: 1.21,
    },
    historicalData: {
      incomeStatement: {
        revenue: {
          YEAR_MINUS_4: 372000,
          YEAR_MINUS_3: 473000,
          YEAR_MINUS_2: 552000,
          LATEST_FY: 571000,
          LTM: 589000,
        },
        grossProfit: {
          YEAR_MINUS_4: 87200,
          YEAR_MINUS_3: 112500,
          YEAR_MINUS_2: 131300,
          LATEST_FY: 138900,
          LTM: 143500,
        },
        ebitda: {
          YEAR_MINUS_4: 46200,
          YEAR_MINUS_3: 59800,
          YEAR_MINUS_2: 69300,
          LATEST_FY: 72700,
          LTM: 74600,
        },
        ebit: {
          YEAR_MINUS_4: 35100,
          YEAR_MINUS_3: 47300,
          YEAR_MINUS_2: 55800,
          LATEST_FY: 58900,
          LTM: 60600,
        },
        netIncome: {
          YEAR_MINUS_4: 25900,
          YEAR_MINUS_3: 35600,
          YEAR_MINUS_2: 42800,
          LATEST_FY: 44600,
          LTM: 45800,
        },
        eps: {
          YEAR_MINUS_4: 12.7,
          YEAR_MINUS_3: 17.5,
          YEAR_MINUS_2: 21.2,
          LATEST_FY: 22.1,
          LTM: 22.7,
        },
        effectiveTaxRate: {
          YEAR_MINUS_4: 0.22,
          YEAR_MINUS_3: 0.22,
          YEAR_MINUS_2: 0.21,
          LATEST_FY: 0.21,
          LTM: 0.21,
        },
        interestExpense: {
          YEAR_MINUS_4: 2800,
          YEAR_MINUS_3: 3000,
          YEAR_MINUS_2: 3250,
          LATEST_FY: 3480,
          LTM: 3520,
        },
        sbc: {
          YEAR_MINUS_4: 340,
          YEAR_MINUS_3: 370,
          YEAR_MINUS_2: 390,
          LATEST_FY: 430,
          LTM: 440,
        },
        dividendsPerShare: {
          YEAR_MINUS_4: 6.5,
          YEAR_MINUS_3: 8,
          YEAR_MINUS_2: 10,
          LATEST_FY: 11.5,
          LTM: 12,
        },
      },
      cashFlow: {
        operatingCashFlow: {
          YEAR_MINUS_4: 40500,
          YEAR_MINUS_3: 51200,
          YEAR_MINUS_2: 60200,
          LATEST_FY: 62100,
          LTM: 64800,
        },
        freeCashFlow: {
          YEAR_MINUS_4: 25300,
          YEAR_MINUS_3: 34100,
          YEAR_MINUS_2: 40200,
          LATEST_FY: 41800,
          LTM: 43500,
        },
        depreciationAndAmortization: {
          YEAR_MINUS_4: 11100,
          YEAR_MINUS_3: 12500,
          YEAR_MINUS_2: 13500,
          LATEST_FY: 13800,
          LTM: 14000,
        },
        capex: {
          YEAR_MINUS_4: 15200,
          YEAR_MINUS_3: 17100,
          YEAR_MINUS_2: 20000,
          LATEST_FY: 20300,
          LTM: 21300,
        },
      },
      workingCapital: {
        receivables: {
          YEAR_MINUS_4: 58200,
          YEAR_MINUS_3: 63300,
          YEAR_MINUS_2: 68400,
          LATEST_FY: 69500,
          LTM: 70800,
        },
        inventory: {
          YEAR_MINUS_4: 46900,
          YEAR_MINUS_3: 53100,
          YEAR_MINUS_2: 57800,
          LATEST_FY: 58900,
          LTM: 60400,
        },
        accountsPayable: {
          YEAR_MINUS_4: 41500,
          YEAR_MINUS_3: 45700,
          YEAR_MINUS_2: 50100,
          LATEST_FY: 51600,
          LTM: 52600,
        },
        deferredRevenue: {
          YEAR_MINUS_4: 9300,
          YEAR_MINUS_3: 9800,
          YEAR_MINUS_2: 10200,
          LATEST_FY: 10500,
          LTM: 10800,
        },
      },
    },
    balanceSheetBridgeInputs: {
      cashAndCashEquivalents: 81000,
      marketableSecurities: 16500,
      grossDebt: 149000,
      leaseLiabilities: 22000,
      minorityInterest: 3900,
      preferredEquity: 0,
      pensionDeficit: 7100,
      otherClaims: 5900,
    },
    debtDetailInputs: {
      averageDebtMaturityYears: 5.7,
      averageDebtCost: 0.046,
      fixedVsFloatingMixPercent: 68,
      debtCurrencyMix: { SEK: 58, EUR: 26, USD: 16 },
    },
    leaseInputs: {
      annualLeaseExpense: 3100,
      leaseDurationYears: 6,
      impliedLeaseDiscountRate: 0.052,
    },
    forecastInputs: {
      revenueGrowthAssumption: 0.05,
      targetOperatingMargin: 0.11,
      targetTaxRate: 0.21,
      targetReinvestmentRate: 0.31,
      targetRoeOrRoic: 0.14,
    },
    riskWaccInputs: {
      riskfreeRate: 0.0238,
      equityRiskPremium: 0.0505,
      countryRiskPremium: 0.0035,
      beta: 1.21,
      preTaxCostOfDebt: 0.05,
      targetDebtToCapital: 0.36,
      marginalTaxRate: 0.21,
    },
    betaPolicyInputs: {
      marketDebtToEquity: 0.45,
      selectedTaxRate: 0.21,
    },
    waccFoundationInputs: {
      preTaxCostOfDebt: 0.05,
      costOfDebtSource: "Mock / Foundation scaffold",
      notes: "Scaffold pre-tax cost of debt for SEK valuation-currency WACC foundation QA.",
    },
    intrinsicValueFoundationInputs: {
      selectedDilutedShares: 2010,
      shareUnit: "millions",
      selectedSharesSource: "LTM historical weighted average diluted shares (millions)",
      currentSharePrice: 276.4,
      priceCurrency: "SEK",
      fxRateToValuationCurrency: 1,
      notes: "Mock / foundation scaffold share count — not live company data.",
    },
    terminalValueInputs: {
      terminalGrowthRate: 0.02,
      terminalRoiOrRoic: 0.11,
      terminalMargin: 0.1,
      terminalMethod: "Hybrid",
    },
    decisionLayerInputs: {
      minimumMOSForApprove: 0.09,
      watchlistMOSFloor: 0.035,
      hardExclusionTags: [],
    },
    scenarioSensitivityInputs: {
      baseCaseWeight: 0.58,
      bullCaseWeight: 0.22,
      bearCaseWeight: 0.2,
      discountRateShockBps: 80,
      terminalGrowthShockBps: 35,
    },
    accountingAdjustmentInputs: {
      normalizeOneOffItems: true,
      capitalizeRAndD: false,
      sbcTreatment: "As Expense",
      leaseTreatment: "Debt-like",
    },
    forecastData: {
      baseCaseRevenueGrowthByPeriod: {
        YEAR_PLUS_1: 0.055,
        YEAR_PLUS_2: 0.052,
        YEAR_PLUS_3: 0.048,
      },
      baseCaseOperatingMarginByPeriod: {
        YEAR_PLUS_1: 0.104,
        YEAR_PLUS_2: 0.107,
        YEAR_PLUS_3: 0.11,
      },
      capexAsPercentRevenueByPeriod: {
        YEAR_PLUS_1: 0.036,
        YEAR_PLUS_2: 0.036,
        YEAR_PLUS_3: 0.035,
      },
      narrative: "Cycle-aware growth with electrification investment tailwind.",
    },
    valuationResult: {
      forecastFadeResult: {
        revenueGrowthPath: {
          YEAR_PLUS_1: 0.055,
          YEAR_PLUS_2: 0.052,
          YEAR_PLUS_3: 0.048,
          YEAR_PLUS_6: 0.034,
          YEAR_PLUS_10: 0.025,
        },
        operatingMarginPath: {
          YEAR_PLUS_1: 0.104,
          YEAR_PLUS_2: 0.107,
          YEAR_PLUS_3: 0.11,
          YEAR_PLUS_10: 0.098,
        },
        fadeNarrative: "Fade to mature industrial vehicle benchmark.",
      },
      reinvestmentFcffResult: {
        reinvestmentRatePath: {
          YEAR_PLUS_1: 0.33,
          YEAR_PLUS_2: 0.32,
          YEAR_PLUS_3: 0.31,
        },
        fcffPath: {
          YEAR_PLUS_1: 45100,
          YEAR_PLUS_2: 46800,
          YEAR_PLUS_3: 48900,
        },
        notes: "Placeholder FCFF path only.",
      },
      riskWaccResult: {
        costOfEquity: 0.088,
        costOfDebtAfterTax: 0.04,
        wacc: 0.073,
        beta: 1.21,
        erp: 0.0505,
      },
      terminalValueResult: {
        terminalMethod: "Hybrid",
        terminalValue: 701000,
        terminalGrowthRate: 0.02,
        terminalYear: "YEAR_PLUS_10",
      },
      firmToEquityBridgeResult: {
        enterpriseValue: 738000,
        cashAndInvestments: 97500,
        totalDebtAndDebtLikeClaims: 171000,
        minorityInterest: 3900,
        preferredEquity: 0,
        pensionAndOtherClaims: 13000,
        equityValue: 647600,
      },
      shareCountResult: {
        historicalWeightedAverageDilutedShares: 2010,
        finalShareCountUsed: 2010,
        sbcDilutionAssumption: 0.004,
      },
      perShareValuationResult: {
        intrinsicValuePerShare: 337.2,
        entryPrice: 276.4,
        exitPrice12m: 321.8,
        return12mFromEntry: 0.164,
        exitPrice3y: 395.1,
        return3yFromEntry: 0.429,
        finalMOS: 0.097,
      },
      decisionResult: {
        decisionStatus: "Approve",
        statusNote: "Commercial cycle risk remains, but balance sheet is solid.",
        blockingFlags: [],
        reviewFlag: {
          category: "Financial Health",
          severity: "Watch",
          note: "Debt profile is manageable but must be monitored.",
        },
      },
      modelVersion: "phase2-placeholder-v1",
      calculatedAt: "2026-05-24",
    },
    reviewSummary: {
      worstSeverity: "Watch",
      contributingCategories: ["Financial Health", "Currency Review"],
      categoryStatuses: {
        ...buildCategoryStatuses("Info"),
        "Financial Health": "Watch",
        "Currency Review": "Watch",
      },
      note: "Cross-currency sensitivity and cycle risk under active review.",
    },
    dashboardRow: {
      companyLogoUrl: "https://logo.clearbit.com/volvogroup.com",
      companyName: "Volvo",
      ticker: "VOLV-B",
      exchange: "STO",
      ismSector: "Industrials",
      damodaranIndustrialBenchmark: "Auto & Truck",
      currentPrice: 304.5,
      marketCap: 620000000000,
      valuationCurrency: "SEK",
      intrinsicValuePerShare: 337.2,
      finalMOS: 0.097,
      entryPrice: 276.4,
      exitPrice12m: 321.8,
      return12mFromEntry: 0.164,
      exitPrice3y: 395.1,
      return3yFromEntry: 0.429,
      decisionStatus: "Approve",
      reviewFlag: "Watch",
      statusNote: "Commercial cycle risk remains, but balance sheet is solid.",
      beta: 1.21,
      erp: 0.0505,
      wacc: 0.073,
      forecastQuality: "Info",
      fadeQuality: "Watch",
      terminalReadiness: "Info",
      financialHealth: "Watch",
      businessQuality: "Info",
      shareCountReview: "Info",
      sbcDilutionReview: "Info",
      currencyReview: "Watch",
      lastUpdated: "2026-05-24",
      websiteUrl: "https://www.volvogroup.com",
      openCompanyUrl: "/companies/VOLV-B",
    },
    lastUpdated: "2026-05-24",
    availableHistoricalPeriods: standardHistoricalPeriods,
  },
];

export const dashboardRows: DashboardCompanyRow[] = mockCompanies.map(
  (company) => company.dashboardRow,
);

export function getMockCompanyByTicker(cleanTicker: string) {
  return mockCompanies.find(
    (company) =>
      company.identity.cleanTicker.toLowerCase() === cleanTicker.toLowerCase(),
  );
}
