import type {
  ApiProviderConfig,
  BetaReferenceData,
  CountryRiskErpData,
  CurrencyMapRow,
  DailyRefreshStatus,
  DamodaranDataSection,
  ForecastFadeRules,
  FxPairRateRow,
  RiskfreeRateRow,
  SectorIndustryMapping,
} from "@/lib/types";
import {
  buildFxPairRowsFromCurrencyMap,
  getSelectedRiskfreeRate,
  getRiskfreeStatus,
} from "@/lib/data-hub/rateSelectors";

const today = "2026-05-24";

export const riskfreeRateConfigs: RiskfreeRateRow[] = [
  {
    id: "riskfree_USD",
    currencyCode: "USD",
    currencyName: "US Dollar",
    riskfreeProxy: "US 10Y Treasury",
    fredSeriesId: "DGS10",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.0415,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org/series/DGS10",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "Valuation currency mapping active. No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_EUR",
    currencyCode: "EUR",
    currencyName: "Euro",
    riskfreeProxy: "German 10Y Bund Proxy",
    fredSeriesId: "IRLTLT01DEM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.0238,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org/series/IRLTLT01DEM156N",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_SEK",
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    riskfreeProxy: "Sweden 10Y Government Bond",
    fredSeriesId: "IRLTLT01SEM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.025,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org/series/IRLTLT01SEM156N",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_NOK",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    riskfreeProxy: "Norway 10Y Government Bond Proxy",
    fredSeriesId: "IRLTLT01NOM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.04,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_DKK",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    riskfreeProxy: "Denmark 10Y Government Bond Proxy",
    fredSeriesId: "IRLTLT01DKM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.024,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_GBP",
    currencyCode: "GBP",
    currencyName: "British Pound",
    riskfreeProxy: "UK 10Y Gilt Proxy",
    fredSeriesId: "IRLTLT01GBM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.042,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_CHF",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    riskfreeProxy: "Switzerland 10Y Government Bond Proxy",
    fredSeriesId: "IRLTLT01CHM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.007,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_CAD",
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    riskfreeProxy: "Canada 10Y Government Bond Proxy",
    fredSeriesId: "IRLTLT01CAM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.035,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_AUD",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    riskfreeProxy: "Australia 10Y Government Bond Proxy",
    fredSeriesId: "IRLTLT01AUM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.043,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
  {
    id: "riskfree_JPY",
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    riskfreeProxy: "Japan 10Y Government Bond Proxy",
    fredSeriesId: "IRLTLT01JPM156N",
    autoImportEnabled: true,
    liveRiskfreeRate: 0.012,
    manualOverrideRate: null,
    selectedRiskfreeRate: null,
    sourceName: "FRED (planned for Phase 4B)",
    sourceUrl: "https://fred.stlouisfed.org",
    sourceUpdateDate: today,
    importedLastUpdated: null,
    status: "",
    notes: "No live provider call in Phase 4A.",
  },
];

export const currencyMapRows: CurrencyMapRow[] = [
  {
    id: "currency_USD",
    currencyCode: "USD",
    currencyName: "US Dollar",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "US 10Y Treasury",
    notes: "Default active currency.",
  },
  {
    id: "currency_EUR",
    currencyCode: "EUR",
    currencyName: "Euro",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "German 10Y Bund Proxy",
    notes: "Default active currency.",
  },
  {
    id: "currency_SEK",
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "Sweden 10Y Government Bond",
    notes: "Default active currency.",
  },
  {
    id: "currency_NOK",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "Norway 10Y Government Bond Proxy",
    notes: "Default active currency.",
  },
  {
    id: "currency_DKK",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "Denmark 10Y Government Bond Proxy",
    notes: "Default active currency.",
  },
  {
    id: "currency_GBP",
    currencyCode: "GBP",
    currencyName: "British Pound",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "UK 10Y Gilt Proxy",
    notes: "Default active currency.",
  },
  {
    id: "currency_CHF",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "Switzerland 10Y Government Bond Proxy",
    notes: "Default active currency.",
  },
  {
    id: "currency_CAD",
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "Canada 10Y Government Bond Proxy",
    notes: "Default active currency.",
  },
  {
    id: "currency_AUD",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "Australia 10Y Government Bond Proxy",
    notes: "Default active currency.",
  },
  {
    id: "currency_JPY",
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    active: true,
    usedAsReporting: true,
    usedAsValuation: true,
    usedAsTrading: true,
    riskfreeRequired: true,
    defaultRiskfreeProxy: "Japan 10Y Government Bond Proxy",
    notes: "Default active currency.",
  },
];

export const fxRateConfigs: FxPairRateRow[] =
  buildFxPairRowsFromCurrencyMap(currencyMapRows);

export const valuationCurrencyRiskfreeExamples = [
  "USD -> US 10Y Treasury / DGS10",
  "EUR -> German 10Y Bund proxy / IRLTLT01DEM156N",
  "SEK -> Sweden 10Y Government Bond / IRLTLT01SEM156N",
];

for (const row of riskfreeRateConfigs) {
  row.selectedRiskfreeRate = getSelectedRiskfreeRate(row);
  row.status = getRiskfreeStatus(row);
}

export const countryRiskErpData: CountryRiskErpData[] = [
  {
    country: "United States",
    countryCode: "US",
    sovereignRating: "AA+",
    countryRiskPremium: 0,
    equityRiskPremium: 4.7,
    asOfDate: "2026-05-24",
  },
  {
    country: "Sweden",
    countryCode: "SE",
    sovereignRating: "AAA",
    countryRiskPremium: 0.35,
    equityRiskPremium: 5.05,
    asOfDate: "2026-05-24",
  },
];

export const damodaranDataSections: DamodaranDataSection[] = [
  {
    sectionName: "Cost of Capital by Industry",
    versionTag: "placeholder-v1",
    asOfDate: "2026-05-24",
    notes: "Placeholder metadata only. No live ingestion in this phase.",
  },
  {
    sectionName: "Margins and Sales to Capital",
    versionTag: "placeholder-v1",
    asOfDate: "2026-05-24",
    notes: "Used for future benchmark matching.",
  },
];

export const sectorIndustryMappings: SectorIndustryMapping[] = [
  {
    ismSector: "Information Technology",
    internalIndustryName: "Mega-cap Software Platforms",
    damodaranIndustry: "Software (System & Application)",
  },
  {
    ismSector: "Communication Services",
    internalIndustryName: "Media and Entertainment",
    damodaranIndustry: "Entertainment",
  },
  {
    ismSector: "Industrials",
    internalIndustryName: "Commercial Vehicles and Machinery",
    damodaranIndustry: "Auto & Truck",
  },
];

export const betaReferenceData: BetaReferenceData[] = [
  {
    benchmarkName: "Damodaran Industry Beta",
    industry: "Software (System & Application)",
    unleveredBeta: 1.04,
    releveredBeta: 1.12,
    asOfDate: "2026-05-24",
  },
  {
    benchmarkName: "Damodaran Industry Beta",
    industry: "Entertainment",
    unleveredBeta: 0.95,
    releveredBeta: 1.08,
    asOfDate: "2026-05-24",
  },
];

export const forecastFadeRules: ForecastFadeRules[] = [
  {
    ruleSetName: "Large Cap Base Rule",
    fadeStartYear: 4,
    fadeEndYear: 10,
    targetMarginConvergence: "Converge to industry median operating margin",
    targetGrowthConvergence: "Converge to nominal GDP + inflation proxy",
  },
];

export const apiProviderConfigs: ApiProviderConfig[] = [
  {
    provider: "FRED",
    keyEnvVarName: "FRED_API_KEY",
    purpose: "Riskfree rates and macro proxies",
    status: "Ready for Integration",
    notes: "No live calls in Phase 2.",
  },
  {
    provider: "EODHD",
    keyEnvVarName: "EODHD_API_KEY_1",
    purpose: "Market data backup provider",
    status: "Ready for Integration",
    notes: "No live calls in Phase 2.",
  },
  {
    provider: "Firebase",
    keyEnvVarName: "NEXT_PUBLIC_FIREBASE_API_KEY",
    purpose: "Client config for future Firestore usage",
    status: "Ready for Integration",
    notes: "No Firestore read/write in Phase 2.",
  },
];

export const mockDailyRefreshStatus: DailyRefreshStatus = {
  startedAt: "2026-05-24T06:00:00.000Z",
  finishedAt: "2026-05-24T06:00:01.000Z",
  success: true,
  riskfreeRefreshStatus: "Configured / Pending Phase 4B",
  fxRefreshStatus: "Configured / Pending Phase 4B",
  providersUsed: ["FRED (planned)", "EODHD/FMP/Finnhub/MarketStack/Alpha Vantage (planned)"],
  warnings: ["No live provider calls in Phase 4A."],
  errors: [],
  lastSuccessfulRefreshAt: "2026-05-24T06:00:01.000Z",
  source: "phase4a-refresh-architecture",
  status: "Configured / Pending Phase 4B",
};
