import { CompanyEngineResult } from "@/lib/types";

export const mockCompanies: CompanyEngineResult[] = [
  {
    companyName: "Microsoft",
    fullTicker: "MSFT:NASDAQ",
    cleanTicker: "MSFT",
    exchange: "NASDAQ",
    valuationCurrency: "USD",
    reportingCurrency: "USD",
    tradingCurrency: "USD",
    currentPrice: 432.18,
    marketCap: 3210000000000,
    intrinsicValuePerShare: 478.4,
    entryPrice: 389.6,
    exitPrice12m: 452.3,
    exitPrice3y: 561.9,
    finalMOS: 9.66,
    decisionStatus: "Approve",
    reviewFlag: "Green",
    statusNote: "Stable growth and high quality cash conversion.",
    lastUpdated: "2026-05-24",
  },
  {
    companyName: "Disney",
    fullTicker: "DIS:NYSE",
    cleanTicker: "DIS",
    exchange: "NYSE",
    valuationCurrency: "USD",
    reportingCurrency: "USD",
    tradingCurrency: "USD",
    currentPrice: 112.74,
    marketCap: 207000000000,
    intrinsicValuePerShare: 124.1,
    entryPrice: 95.2,
    exitPrice12m: 118.6,
    exitPrice3y: 143.4,
    finalMOS: 9.15,
    decisionStatus: "Watchlist",
    reviewFlag: "Yellow",
    statusNote: "Parks strength offsets streaming margin uncertainty.",
    lastUpdated: "2026-05-24",
  },
  {
    companyName: "Volvo",
    fullTicker: "VOLV-B:STO",
    cleanTicker: "VOLV-B",
    exchange: "STO",
    valuationCurrency: "SEK",
    reportingCurrency: "SEK",
    tradingCurrency: "SEK",
    currentPrice: 304.5,
    marketCap: 620000000000,
    intrinsicValuePerShare: 337.2,
    entryPrice: 276.4,
    exitPrice12m: 321.8,
    exitPrice3y: 395.1,
    finalMOS: 9.7,
    decisionStatus: "Approve",
    reviewFlag: "Green",
    statusNote: "Commercial cycle risk remains, but balance sheet is solid.",
    lastUpdated: "2026-05-24",
  },
];

export function getMockCompanyByTicker(cleanTicker: string) {
  return mockCompanies.find(
    (company) => company.cleanTicker.toLowerCase() === cleanTicker.toLowerCase(),
  );
}
