export const COLLECTIONS = {
  companies: "companies",
  companyInputs: "companyInputs",
  valuationResults: "valuationResults",
  dashboardRows: "dashboardRows",
  referenceData: "referenceData",
  currencyMap: "currencyMap",
  riskfreeRates: "riskfreeRates",
  fxRates: "fxRates",
  damodaranData: "damodaranData",
  damodaranDatasetRegister: "damodaranDatasetRegister",
  damodaranIndustryMaster: "damodaranIndustryMaster",
  damodaranCoverageMatrix: "damodaranCoverageMatrix",
  damodaranImportSummary: "damodaranImportSummary",
  damodaranRawDatasetRows: "damodaranRawDatasetRows",
  countryErpRows: "countryErpRows",
  regionalErpRows: "regionalErpRows",
  countryRegionalGroupMap: "countryRegionalGroupMap",
  regionalGroupDefinitions: "regionalGroupDefinitions",
  countryRiskErpSourceNotes: "countryRiskErpSourceNotes",
  erpUsageRules: "erpUsageRules",
  weightedErpFormulaGuide: "weightedErpFormulaGuide",
  countryRiskErpImportStatus: "countryRiskErpImportStatus",
  ismSectorRows: "ismSectorRows",
  sectorIndustryMappings: "sectorIndustryMappings",
  sectorMappingRules: "sectorMappingRules",
  sectorMappingValidationValues: "sectorMappingValidationValues",
  sectorMappingStatusValues: "sectorMappingStatusValues",
  sectorMappingReadiness: "sectorMappingReadiness",
  sectorMappingImportStatus: "sectorMappingImportStatus",
  sectorIndustryMapping: "sectorIndustryMapping",
  betaReferenceData: "betaReferenceData",
  forecastFadeRules: "forecastFadeRules",
  apiProviderConfigs: "apiProviderConfigs",
  settings: "settings",
  buildStatus: "buildStatus",
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
