/**
 * Manual Inputs → Valuation Engine wiring contract.
 * Part 2B-2: current price + required MOS are market_overlay_wired (MOS/Dashboard only).
 * All other persistable fields remain not_wired_yet for the valuation chain.
 */

export const MANUAL_INPUT_WIRING_PHASE = "2B-2-market-overlay-wired" as const;

export type ManualInputEngineGroup =
  | "Identity / Metadata"
  | "Market Data"
  | "Currency / FX"
  | "Industry Benchmark"
  | "Beta / WACC"
  | "Forecast / Fade"
  | "Reinvestment / FCFF"
  | "Terminal Value"
  | "Firm-to-Equity Bridge"
  | "Share Count / Intrinsic Value"
  | "MOS / Decision Foundation"
  | "Notes only / display only";

export type ManualInputWiringFieldStatus = "not_wired_yet" | "market_overlay_wired";

export const MARKET_OVERLAY_WIRED_CONTRACT_FIELD_KEYS = [
  "overrides.market.currentPrice",
  "overrides.decisionLayerInputs.minimumMOSForApprove",
] as const;

export interface ManualInputWiringFieldContract {
  /** Stable key — persisted overrides use `overrides.*`; workspace-only use `workspace.*`. */
  fieldKey: string;
  label: string;
  engineGroup: ManualInputEngineGroup;
  /** Target foundation engine or surface (future). */
  engineTarget: string;
  futureUsage: string;
  unit: string;
  status: ManualInputWiringFieldStatus;
  allowedForFutureEngineWiring: boolean;
  /** True when field is written to `companyInputs` on Save. */
  persistable: boolean;
  /** Part 2B-1: always false until engine_wired phase. */
  invalidatesValuationCacheWhenSaved: boolean;
  notes: string;
}

const NOT_WIRED: ManualInputWiringFieldStatus = "not_wired_yet";
const MARKET_OVERLAY_WIRED: ManualInputWiringFieldStatus = "market_overlay_wired";

export const MANUAL_INPUT_WIRING_CONTRACT: readonly ManualInputWiringFieldContract[] = [
  // —— Identity / Metadata ——
  {
    fieldKey: "overrides.identity.companyName",
    label: "Company name",
    engineGroup: "Identity / Metadata",
    engineTarget: "Company Workspace (display)",
    futureUsage: "Workspace labels only — not a valuation engine input.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Persisted for Inputs tab; does not map to foundation fingerprint today.",
  },
  {
    fieldKey: "overrides.identity.exchange",
    label: "Exchange",
    engineGroup: "Identity / Metadata",
    engineTarget: "Company Workspace (display)",
    futureUsage: "Display metadata only.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.identity.websiteUrl",
    label: "Website URL",
    engineGroup: "Identity / Metadata",
    engineTarget: "Company Workspace (display)",
    futureUsage: "Display metadata only.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.identity.countryOfRisk",
    label: "Country of risk",
    engineGroup: "Identity / Metadata",
    engineTarget: "WACC Foundation",
    futureUsage: "Country-of-risk ERP / CRP selection when engine_wired.",
    unit: "country code",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Maps to company.identity.countryOfRisk on merge.",
  },
  {
    fieldKey: "workspace.identity.fullTicker",
    label: "Full ticker",
    engineGroup: "Identity / Metadata",
    engineTarget: "Routing (read-only)",
    futureUsage: "Not saved in Part 2A payload.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Workspace display only.",
  },
  {
    fieldKey: "workspace.identity.cleanTicker",
    label: "Clean ticker",
    engineGroup: "Identity / Metadata",
    engineTarget: "Routing (read-only)",
    futureUsage: "Document key — not overridable.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "workspace.identity.ismSector",
    label: "ISM-sector (company record)",
    engineGroup: "Notes only / display only",
    engineTarget: "ISM display map",
    futureUsage: "Display-only — never a primary valuation driver.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "ISM-sector is display-only per architecture rules.",
  },
  {
    fieldKey: "overrides.companySetup.valuationDate",
    label: "Valuation date",
    engineGroup: "Identity / Metadata",
    engineTarget: "Company Workspace (scaffold)",
    futureUsage: "Valuation date context for future reporting — not in foundation fingerprint today.",
    unit: "date",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Market Data ——
  {
    fieldKey: "overrides.market.currentPrice",
    label: "Current share price (currentSharePrice)",
    engineGroup: "Market Data",
    engineTarget: "Market Overlay / MOS / Decision Foundation",
    futureUsage:
      "Wired Part 2B-2: MOS + Dashboard presentation only; valuation foundation cache STALE overlay.",
    unit: "per share",
    status: MARKET_OVERLAY_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Does not recompute Beta→Intrinsic chain.",
  },
  {
    fieldKey: "overrides.market.marketCap",
    label: "Market cap",
    engineGroup: "Market Data",
    engineTarget: "Company Workspace (scaffold)",
    futureUsage: "Scaffold / cross-check — not in foundation engines today.",
    unit: "absolute currency",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Saved from workspace marketCapMillions × 1e6.",
  },
  {
    fieldKey: "workspace.market.marketCapMillions",
    label: "Market cap (m) — workspace",
    engineGroup: "Market Data",
    engineTarget: "Save mapping",
    futureUsage: "UI millions field → overrides.market.marketCap.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Workspace representation only.",
  },
  {
    fieldKey: "overrides.market.manualShareCountOverride",
    label: "Manual share count override",
    engineGroup: "Market Data",
    engineTarget: "Intrinsic Value / Share (future)",
    futureUsage: "Optional share override when engine_wired.",
    unit: "shares",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.market.beta",
    label: "Market beta (scaffold)",
    engineGroup: "Market Data",
    engineTarget: "Risk/WACC scaffold",
    futureUsage: "Distinct from Damodaran beta policy; future WACC scaffold only.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Also mapped to overrides.riskWaccInputs.beta when saved.",
  },

  // —— Currency / FX ——
  {
    fieldKey: "overrides.currencies.reportingCurrency",
    label: "Reporting currency",
    engineGroup: "Currency / FX",
    engineTarget: "WACC / display",
    futureUsage: "Reporting context; valuation fingerprint includes reportingCurrency when wired.",
    unit: "ISO currency",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.currencies.valuationCurrency",
    label: "Valuation currency",
    engineGroup: "Currency / FX",
    engineTarget: "WACC Foundation",
    futureUsage: "Riskfree / WACC currency anchor when engine_wired.",
    unit: "ISO currency",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.currencies.tradingCurrency",
    label: "Trading currency",
    engineGroup: "Currency / FX",
    engineTarget: "MOS / Decision Foundation (FX)",
    futureUsage: "Price vs intrinsic FX conversion when engine_wired.",
    unit: "ISO currency",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.currencies.fxPairToValuation",
    label: "FX pair to valuation",
    engineGroup: "Currency / FX",
    engineTarget: "MOS / Intrinsic (FX)",
    futureUsage: "FX pair label for future conversion scaffold.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.currencies.note",
    label: "Currency note",
    engineGroup: "Notes only / display only",
    engineTarget: "Notes",
    futureUsage: "Analyst note — not used in engine math.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "workspace.currencies.reviewStatus",
    label: "Currency review status",
    engineGroup: "Notes only / display only",
    engineTarget: "Currency config (read-only)",
    futureUsage: "Not persisted in Part 2A save payload.",
    unit: "status",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Industry Benchmark ——
  {
    fieldKey: "overrides.identity.damodaranIndustrialBenchmark",
    label: "Damodaran Industrial Benchmark (primary)",
    engineGroup: "Industry Benchmark",
    engineTarget: "Beta / Forecast-Fade / chain gate",
    futureUsage: "Primary benchmark anchor for beta pull keys and forecast-fade when engine_wired.",
    unit: "benchmark name",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Saved from workspace.benchmark.selected.",
  },
  {
    fieldKey: "workspace.benchmark.selected",
    label: "Benchmark dropdown (workspace)",
    engineGroup: "Industry Benchmark",
    engineTarget: "Save mapping",
    futureUsage: "UI field → overrides.identity.damodaranIndustrialBenchmark.",
    unit: "benchmark name",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Does not trigger valuation run in Part 2A/2B-1.",
  },
  {
    fieldKey: "workspace.benchmark.ismSectorDisplay",
    label: "ISM-sector (display-only)",
    engineGroup: "Notes only / display only",
    engineTarget: "ISM display map",
    futureUsage: "Never wired to valuation engines.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "workspace.benchmark.templateStatus",
    label: "Template status",
    engineGroup: "Notes only / display only",
    engineTarget: "Industry Benchmark Config",
    futureUsage: "Read-only scaffold from mapping tables.",
    unit: "status",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "workspace.benchmark.universeOptions",
    label: "Benchmark universe options",
    engineGroup: "Notes only / display only",
    engineTarget: "Dropdown options",
    futureUsage: "UI helper list — not persisted.",
    unit: "list",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Beta / WACC ——
  {
    fieldKey: "overrides.betaPolicyInputs.marketDebtToEquity",
    label: "Market D/E (beta policy)",
    engineGroup: "Beta / WACC",
    engineTarget: "Beta Policy / WACC Foundation",
    futureUsage: "Relevering and capital structure when engine_wired.",
    unit: "ratio",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Workspace: financial.marketDebtToEquity.",
  },
  {
    fieldKey: "overrides.betaPolicyInputs.selectedTaxRate",
    label: "Selected tax rate (beta policy)",
    engineGroup: "Beta / WACC",
    engineTarget: "Beta Policy / WACC Foundation",
    futureUsage: "Relevering tax input when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Workspace: financial.selectedTaxRateBeta.",
  },
  {
    fieldKey: "overrides.riskWaccInputs.riskfreeRate",
    label: "Risk-free rate",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "Cost of equity / WACC when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.riskWaccInputs.equityRiskPremium",
    label: "Equity risk premium",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "ERP input when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.riskWaccInputs.countryRiskPremium",
    label: "Country risk premium",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "CRP when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.riskWaccInputs.preTaxCostOfDebt",
    label: "Pre-tax cost of debt",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "WACC debt leg when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.riskWaccInputs.targetDebtToCapital",
    label: "Target debt to capital",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "Capital structure scaffold when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.riskWaccInputs.marginalTaxRate",
    label: "Marginal tax rate",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "Tax shield when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.riskWaccInputs.beta",
    label: "Risk beta (from market field)",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "Scaffold beta on riskWaccInputs when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Duplicated from overrides.market.beta on save.",
  },
  {
    fieldKey: "overrides.waccFoundationInputs.preTaxCostOfDebt",
    label: "WACC foundation pre-tax cost of debt",
    engineGroup: "Beta / WACC",
    engineTarget: "WACC Foundation",
    futureUsage: "Explicit WACC scaffold override when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Workspace: financial.waccPreTaxCostOfDebt.",
  },

  // —— Forecast / Fade ——
  {
    fieldKey: "overrides.forecastInputs.revenueGrowthAssumption",
    label: "Revenue growth assumption",
    engineGroup: "Forecast / Fade",
    engineTarget: "Forecast & Fade Foundation",
    futureUsage: "Forecast scaffold when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.forecastInputs.targetOperatingMargin",
    label: "Target operating margin",
    engineGroup: "Forecast / Fade",
    engineTarget: "Forecast & Fade Foundation",
    futureUsage: "Margin scaffold when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.forecastInputs.targetTaxRate",
    label: "Target tax rate",
    engineGroup: "Forecast / Fade",
    engineTarget: "Forecast & Fade / Reinvestment",
    futureUsage: "Forecast tax scaffold when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.forecastInputs.targetReinvestmentRate",
    label: "Target reinvestment rate",
    engineGroup: "Forecast / Fade",
    engineTarget: "Forecast & Fade Foundation",
    futureUsage: "Reinvestment context when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Reinvestment / FCFF ——
  {
    fieldKey: "overrides.historicalLtm.revenue",
    label: "LTM revenue (m)",
    engineGroup: "Reinvestment / FCFF",
    engineTarget: "Reinvestment / FCFF Foundation (future)",
    futureUsage: "Historical LTM scaffold for FCFF path when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Workspace: historicalPlaceholder.ltmRevenueMillions.",
  },
  {
    fieldKey: "overrides.historicalLtm.freeCashFlow",
    label: "LTM FCF (m)",
    engineGroup: "Reinvestment / FCFF",
    engineTarget: "Reinvestment / FCFF Foundation (future)",
    futureUsage: "LTM FCF scaffold when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Workspace: historicalPlaceholder.ltmFcfMillions.",
  },
  {
    fieldKey: "workspace.historicalPlaceholder.periods",
    label: "Available historical periods",
    engineGroup: "Notes only / display only",
    engineTarget: "Historical scaffold",
    futureUsage: "Read-only period list — not persisted.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Terminal Value ——
  {
    fieldKey: "overrides.terminalValueInputs.terminalGrowthRate",
    label: "Terminal growth rate",
    engineGroup: "Terminal Value",
    engineTarget: "Terminal Value Foundation",
    futureUsage: "Gordon growth input when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "In valuation fingerprint today via base company only.",
  },
  {
    fieldKey: "overrides.terminalValueInputs.terminalMargin",
    label: "Terminal margin",
    engineGroup: "Terminal Value",
    engineTarget: "Terminal Value Foundation",
    futureUsage: "Terminal margin scaffold when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.terminalValueInputs.terminalMethod",
    label: "Terminal method",
    engineGroup: "Terminal Value",
    engineTarget: "Terminal Value Foundation",
    futureUsage: "Gordon / Exit / Hybrid selection when engine_wired.",
    unit: "enum",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Firm-to-Equity Bridge ——
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.cashAndCashEquivalents",
    label: "Cash & cash equivalents",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge addition when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.marketableSecurities",
    label: "Marketable securities",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge addition when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.grossDebt",
    label: "Gross debt",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge deduction when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.leaseLiabilities",
    label: "Lease liabilities",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge deduction when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.minorityInterest",
    label: "Minority interest",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge deduction when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.preferredEquity",
    label: "Preferred equity",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge deduction when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.pensionDeficit",
    label: "Pension deficit",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge deduction when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.balanceSheetBridgeInputs.otherClaims",
    label: "Other claims",
    engineGroup: "Firm-to-Equity Bridge",
    engineTarget: "Equity Bridge Foundation",
    futureUsage: "Bridge deduction when engine_wired.",
    unit: "millions",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Share Count / Intrinsic Value ——
  {
    fieldKey: "overrides.intrinsicValueFoundationInputs.selectedDilutedShares",
    label: "Selected diluted shares",
    engineGroup: "Share Count / Intrinsic Value",
    engineTarget: "Intrinsic Value / Share Foundation",
    futureUsage: "Per-share divisor when engine_wired.",
    unit: "shares (unit from shareUnit)",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.intrinsicValueFoundationInputs.shareUnit",
    label: "Share unit",
    engineGroup: "Share Count / Intrinsic Value",
    engineTarget: "Intrinsic Value / Share Foundation",
    futureUsage: "millions | absolute interpretation when engine_wired.",
    unit: "enum",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.intrinsicValueFoundationInputs.selectedSharesSource",
    label: "Shares source label",
    engineGroup: "Share Count / Intrinsic Value",
    engineTarget: "Intrinsic Value / Share Foundation",
    futureUsage: "Provenance label when engine_wired.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.intrinsicValueFoundationInputs.fxRateToValuationCurrency",
    label: "FX rate to valuation currency",
    engineGroup: "Share Count / Intrinsic Value",
    engineTarget: "Intrinsic Value / MOS (FX)",
    futureUsage: "Cross-currency per-share when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— MOS / Decision Foundation ——
  {
    fieldKey: "overrides.decisionLayerInputs.minimumMOSForApprove",
    label: "Required MOS % (minimumMOSForApprove / requiredMosPercent)",
    engineGroup: "MOS / Decision Foundation",
    engineTarget: "Market Overlay / MOS / Decision Foundation",
    futureUsage:
      "Wired Part 2B-2: required MOS threshold for MOS foundation + Dashboard — not Buy/Sell/Hold.",
    unit: "decimal",
    status: MARKET_OVERLAY_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "Does not affect intrinsic value per share.",
  },
  {
    fieldKey: "overrides.decisionLayerInputs.watchlistMOSFloor",
    label: "Watchlist MOS floor",
    engineGroup: "MOS / Decision Foundation",
    engineTarget: "MOS / Decision Foundation",
    futureUsage: "Secondary threshold scaffold when engine_wired.",
    unit: "decimal",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: true,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "overrides.decisionLayerInputs.analystOverrideNote",
    label: "Analyst override note",
    engineGroup: "Notes only / display only",
    engineTarget: "Notes",
    futureUsage: "Text note — not engine math.",
    unit: "text",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: true,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },

  // —— Workspace meta (not saved) ——
  {
    fieldKey: "workspace.persistence",
    label: "Persistence metadata",
    engineGroup: "Notes only / display only",
    engineTarget: "Save status UI",
    futureUsage: "Load/save metadata display.",
    unit: "object",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "workspace.dataSource",
    label: "Base company data source",
    engineGroup: "Notes only / display only",
    engineTarget: "Company record",
    futureUsage: "Firestore vs mock indicator.",
    unit: "enum",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
  {
    fieldKey: "workspace.lastUpdated",
    label: "Company last updated",
    engineGroup: "Notes only / display only",
    engineTarget: "Company record",
    futureUsage: "Base company timestamp.",
    unit: "timestamp",
    status: NOT_WIRED,
    allowedForFutureEngineWiring: false,
    persistable: false,
    invalidatesValuationCacheWhenSaved: false,
    notes: "",
  },
] as const;

/** Leaf paths on ManualInputsWorkspaceModel that must appear in the contract (coverage QA). */
export const MANUAL_INPUTS_WORKSPACE_LEAF_PATHS = [
  "identity.companyName",
  "identity.fullTicker",
  "identity.cleanTicker",
  "identity.exchange",
  "identity.websiteUrl",
  "identity.countryOfRisk",
  "identity.ismSector",
  "identity.damodaranIndustrialBenchmark",
  "currencies.reportingCurrency",
  "currencies.valuationCurrency",
  "currencies.tradingCurrency",
  "currencies.fxPairToValuation",
  "currencies.reviewStatus",
  "currencies.note",
  "companySetup.valuationDate",
  "market.currentPrice",
  "market.marketCapMillions",
  "market.manualShareCountOverride",
  "market.beta",
  "benchmark.selected",
  "benchmark.ismSectorDisplay",
  "benchmark.templateStatus",
  "benchmark.universeOptions",
  "financial.revenueGrowthAssumption",
  "financial.targetOperatingMargin",
  "financial.targetTaxRate",
  "financial.targetReinvestmentRate",
  "financial.riskfreeRate",
  "financial.equityRiskPremium",
  "financial.countryRiskPremium",
  "financial.preTaxCostOfDebt",
  "financial.targetDebtToCapital",
  "financial.marginalTaxRate",
  "financial.marketDebtToEquity",
  "financial.selectedTaxRateBeta",
  "financial.waccPreTaxCostOfDebt",
  "financial.terminalGrowthRate",
  "financial.terminalMethod",
  "financial.terminalMargin",
  "bridge.cashAndCashEquivalents",
  "bridge.marketableSecurities",
  "bridge.grossDebt",
  "bridge.leaseLiabilities",
  "bridge.minorityInterest",
  "bridge.preferredEquity",
  "bridge.pensionDeficit",
  "bridge.otherClaims",
  "sharesAndMos.selectedDilutedShares",
  "sharesAndMos.shareUnit",
  "sharesAndMos.selectedSharesSource",
  "sharesAndMos.fxRateToValuationCurrency",
  "sharesAndMos.minimumMOSForApprove",
  "sharesAndMos.watchlistMOSFloor",
  "sharesAndMos.analystOverrideNote",
  "historicalPlaceholder.ltmRevenueMillions",
  "historicalPlaceholder.ltmFcfMillions",
  "historicalPlaceholder.periods",
] as const;

/** Persisted override keys produced by workspaceModelToSavePayload (QA coverage). */
export const MANUAL_INPUTS_PERSISTED_OVERRIDE_KEYS = [
  "overrides.identity.companyName",
  "overrides.identity.exchange",
  "overrides.identity.websiteUrl",
  "overrides.identity.countryOfRisk",
  "overrides.identity.damodaranIndustrialBenchmark",
  "overrides.currencies.reportingCurrency",
  "overrides.currencies.valuationCurrency",
  "overrides.currencies.tradingCurrency",
  "overrides.currencies.fxPairToValuation",
  "overrides.currencies.note",
  "overrides.companySetup.valuationDate",
  "overrides.market.currentPrice",
  "overrides.market.marketCap",
  "overrides.market.manualShareCountOverride",
  "overrides.market.beta",
  "overrides.forecastInputs.revenueGrowthAssumption",
  "overrides.forecastInputs.targetOperatingMargin",
  "overrides.forecastInputs.targetTaxRate",
  "overrides.forecastInputs.targetReinvestmentRate",
  "overrides.riskWaccInputs.riskfreeRate",
  "overrides.riskWaccInputs.equityRiskPremium",
  "overrides.riskWaccInputs.countryRiskPremium",
  "overrides.riskWaccInputs.preTaxCostOfDebt",
  "overrides.riskWaccInputs.targetDebtToCapital",
  "overrides.riskWaccInputs.marginalTaxRate",
  "overrides.riskWaccInputs.beta",
  "overrides.betaPolicyInputs.marketDebtToEquity",
  "overrides.betaPolicyInputs.selectedTaxRate",
  "overrides.waccFoundationInputs.preTaxCostOfDebt",
  "overrides.terminalValueInputs.terminalGrowthRate",
  "overrides.terminalValueInputs.terminalMargin",
  "overrides.terminalValueInputs.terminalMethod",
  "overrides.balanceSheetBridgeInputs.cashAndCashEquivalents",
  "overrides.balanceSheetBridgeInputs.marketableSecurities",
  "overrides.balanceSheetBridgeInputs.grossDebt",
  "overrides.balanceSheetBridgeInputs.leaseLiabilities",
  "overrides.balanceSheetBridgeInputs.minorityInterest",
  "overrides.balanceSheetBridgeInputs.preferredEquity",
  "overrides.balanceSheetBridgeInputs.pensionDeficit",
  "overrides.balanceSheetBridgeInputs.otherClaims",
  "overrides.intrinsicValueFoundationInputs.selectedDilutedShares",
  "overrides.intrinsicValueFoundationInputs.shareUnit",
  "overrides.intrinsicValueFoundationInputs.selectedSharesSource",
  "overrides.intrinsicValueFoundationInputs.fxRateToValuationCurrency",
  "overrides.decisionLayerInputs.minimumMOSForApprove",
  "overrides.decisionLayerInputs.watchlistMOSFloor",
  "overrides.decisionLayerInputs.analystOverrideNote",
  "overrides.historicalLtm.revenue",
  "overrides.historicalLtm.freeCashFlow",
] as const;

const contractByKey = new Map(
  MANUAL_INPUT_WIRING_CONTRACT.map((entry) => [entry.fieldKey, entry]),
);

export function getManualInputWiringContract(): readonly ManualInputWiringFieldContract[] {
  return MANUAL_INPUT_WIRING_CONTRACT;
}

export function getManualInputWiringByEngine(
  engineGroup: ManualInputEngineGroup,
): ManualInputWiringFieldContract[] {
  return MANUAL_INPUT_WIRING_CONTRACT.filter((entry) => entry.engineGroup === engineGroup);
}

export function isManualInputAllowedForFutureEngineWiring(fieldKey: string): boolean {
  const entry = contractByKey.get(fieldKey);
  return entry?.allowedForFutureEngineWiring === true;
}

export function isManualInputMarketOverlayWired(fieldKey: string): boolean {
  const entry = contractByKey.get(fieldKey);
  return entry?.status === "market_overlay_wired";
}

export function getMarketOverlayWiredContractFields(): ManualInputWiringFieldContract[] {
  return MARKET_OVERLAY_WIRED_CONTRACT_FIELD_KEYS.map(
    (key) => contractByKey.get(key)!,
  ).filter(Boolean);
}

export function getManualInputWiringContractField(
  fieldKey: string,
): ManualInputWiringFieldContract | undefined {
  return contractByKey.get(fieldKey);
}

/** All engine groups in display order. */
export const MANUAL_INPUT_ENGINE_GROUPS: readonly ManualInputEngineGroup[] = [
  "Identity / Metadata",
  "Market Data",
  "Currency / FX",
  "Industry Benchmark",
  "Beta / WACC",
  "Forecast / Fade",
  "Reinvestment / FCFF",
  "Terminal Value",
  "Firm-to-Equity Bridge",
  "Share Count / Intrinsic Value",
  "MOS / Decision Foundation",
  "Notes only / display only",
] as const;

export function resolveWorkspacePathToContractFieldKey(workspacePath: string): string | null {
  const direct = `workspace.${workspacePath}`;
  if (contractByKey.has(direct)) return direct;

  const mapping: Record<string, string> = {
    "identity.companyName": "overrides.identity.companyName",
    "identity.exchange": "overrides.identity.exchange",
    "identity.websiteUrl": "overrides.identity.websiteUrl",
    "identity.countryOfRisk": "overrides.identity.countryOfRisk",
    "identity.damodaranIndustrialBenchmark": "overrides.identity.damodaranIndustrialBenchmark",
    "benchmark.selected": "overrides.identity.damodaranIndustrialBenchmark",
    "companySetup.valuationDate": "overrides.companySetup.valuationDate",
    "market.currentPrice": "overrides.market.currentPrice",
    "market.marketCapMillions": "overrides.market.marketCap",
    "market.manualShareCountOverride": "overrides.market.manualShareCountOverride",
    "market.beta": "overrides.market.beta",
    "currencies.reportingCurrency": "overrides.currencies.reportingCurrency",
    "currencies.valuationCurrency": "overrides.currencies.valuationCurrency",
    "currencies.tradingCurrency": "overrides.currencies.tradingCurrency",
    "currencies.fxPairToValuation": "overrides.currencies.fxPairToValuation",
    "currencies.note": "overrides.currencies.note",
    "financial.revenueGrowthAssumption": "overrides.forecastInputs.revenueGrowthAssumption",
    "financial.targetOperatingMargin": "overrides.forecastInputs.targetOperatingMargin",
    "financial.targetTaxRate": "overrides.forecastInputs.targetTaxRate",
    "financial.targetReinvestmentRate": "overrides.forecastInputs.targetReinvestmentRate",
    "financial.riskfreeRate": "overrides.riskWaccInputs.riskfreeRate",
    "financial.equityRiskPremium": "overrides.riskWaccInputs.equityRiskPremium",
    "financial.countryRiskPremium": "overrides.riskWaccInputs.countryRiskPremium",
    "financial.preTaxCostOfDebt": "overrides.riskWaccInputs.preTaxCostOfDebt",
    "financial.targetDebtToCapital": "overrides.riskWaccInputs.targetDebtToCapital",
    "financial.marginalTaxRate": "overrides.riskWaccInputs.marginalTaxRate",
    "financial.marketDebtToEquity": "overrides.betaPolicyInputs.marketDebtToEquity",
    "financial.selectedTaxRateBeta": "overrides.betaPolicyInputs.selectedTaxRate",
    "financial.waccPreTaxCostOfDebt": "overrides.waccFoundationInputs.preTaxCostOfDebt",
    "financial.terminalGrowthRate": "overrides.terminalValueInputs.terminalGrowthRate",
    "financial.terminalMargin": "overrides.terminalValueInputs.terminalMargin",
    "financial.terminalMethod": "overrides.terminalValueInputs.terminalMethod",
    "bridge.cashAndCashEquivalents": "overrides.balanceSheetBridgeInputs.cashAndCashEquivalents",
    "bridge.marketableSecurities": "overrides.balanceSheetBridgeInputs.marketableSecurities",
    "bridge.grossDebt": "overrides.balanceSheetBridgeInputs.grossDebt",
    "bridge.leaseLiabilities": "overrides.balanceSheetBridgeInputs.leaseLiabilities",
    "bridge.minorityInterest": "overrides.balanceSheetBridgeInputs.minorityInterest",
    "bridge.preferredEquity": "overrides.balanceSheetBridgeInputs.preferredEquity",
    "bridge.pensionDeficit": "overrides.balanceSheetBridgeInputs.pensionDeficit",
    "bridge.otherClaims": "overrides.balanceSheetBridgeInputs.otherClaims",
    "sharesAndMos.selectedDilutedShares":
      "overrides.intrinsicValueFoundationInputs.selectedDilutedShares",
    "sharesAndMos.shareUnit": "overrides.intrinsicValueFoundationInputs.shareUnit",
    "sharesAndMos.selectedSharesSource":
      "overrides.intrinsicValueFoundationInputs.selectedSharesSource",
    "sharesAndMos.fxRateToValuationCurrency":
      "overrides.intrinsicValueFoundationInputs.fxRateToValuationCurrency",
    "sharesAndMos.minimumMOSForApprove": "overrides.decisionLayerInputs.minimumMOSForApprove",
    "sharesAndMos.watchlistMOSFloor": "overrides.decisionLayerInputs.watchlistMOSFloor",
    "sharesAndMos.analystOverrideNote": "overrides.decisionLayerInputs.analystOverrideNote",
    "historicalPlaceholder.ltmRevenueMillions": "overrides.historicalLtm.revenue",
    "historicalPlaceholder.ltmFcfMillions": "overrides.historicalLtm.freeCashFlow",
  };

  return mapping[workspacePath] ?? (contractByKey.has(direct) ? direct : null);
}
